---
dist: bionic
services:
  - docker

language: python
python:
  - "3.7"

env:
#-----------------------------------------------
#
# CentOS
#
#-----------------------------------------------
  - distribution: centos-8
    vagrant_version: latest
  - distribution: centos-8
    vagrant_version: 2.1.0
  - distribution: centos-7
    vagrant_version: latest
  - distribution: centos-7
    vagrant_version: 2.1.0
  - distribution: centos-6
    vagrant_version: latest
  - distribution: centos-6
    vagrant_version: 2.1.0

#--------------------------------
#
# Fedora
#
#--------------------------------
  - distribution: fedora-32
    vagrant_version: latest
  - distribution: fedora-32
    vagrant_version: 2.1.0
  - distribution: fedora-31
    vagrant_version: latest
  - distribution: fedora-31
    vagrant_version: 2.1.0
  - distribution: fedora-30
    vagrant_version: latest
  - distribution: fedora-30
    vagrant_version: 2.1.0
  - distribution: fedora-29
    vagrant_version: latest
  - distribution: fedora-29
    vagrant_version: 2.1.0
  - distribution: fedora-28
    vagrant_version: latest
  - distribution: fedora-28
    vagrant_version: 2.1.0
  - distribution: fedora-27
    vagrant_version: latest
  - distribution: fedora-27
    vagrant_version: 2.1.0
  - distribution: fedora-26
    vagrant_version: latest
  - distribution: fedora-26
    vagrant_version: 2.1.0

#--------------------------------
#
# Ubuntu
#
#--------------------------------
  - distribution: ubuntu-18.04
    vagrant_version: latest
  - distribution: ubuntu-18.04
    vagrant_version: 2.1.0
  - distribution: ubuntu-16.04
    vagrant_version: latest
  - distribution: ubuntu-16.04
    vagrant_version: 2.1.0
  - distribution: ubuntu-14.04
    vagrant_version: latest
  - distribution: ubuntu-14.04
    vagrant_version: 2.1.0
  - distribution: ubuntu-12.04
    vagrant_version: 1.8.0

#--------------------------------
#
# Debian
#
#--------------------------------
  - distribution: debian-10
    vagrant_version: latest
  - distribution: debian-10
    vagrant_version: 2.1.0
  - distribution: debian-9
    vagrant_version: latest
  - distribution: debian-9
    vagrant_version: 2.1.0
  - distribution: debian-8
    vagrant_version: latest
  - distribution: debian-8
    vagrant_version: 2.1.0

#--------------------------------
#
# Oraclelinux
#
#--------------------------------
  - distribution: oraclelinux-8
    vagrant_version: latest
  - distribution: oraclelinux-8
    vagrant_version: 2.1.0
  - distribution: oraclelinux-7
    vagrant_version: latest
  - distribution: oraclelinux-7
    vagrant_version: 2.1.0
  - distribution: oraclelinux-6
    vagrant_version: latest
  - distribution: oraclelinux-6
    vagrant_version: 2.1.0

#--------------------------------
#
# Amazonlinux
#
#--------------------------------
  - distribution: amazonlinux-2
    vagrant_version: latest
  - distribution: amazonlinux-2
    vagrant_version: 2.1.0
  - distribution: amazonlinux-1
    vagrant_version: latest
  - distribution: amazonlinux-1
    vagrant_version: 2.1.0

#--------------------------------
#
# Opensuse
#
#--------------------------------
  - distribution: opensuse-15.1
    vagrant_version: latest
  - distribution: opensuse-15.1
    vagrant_version: 2.1.0
  - distribution: opensuse-15
    vagrant_version: latest
  - distribution: opensuse-15
    vagrant_version: 2.1.0
  - distribution: opensuse-42.3
    vagrant_version: latest
  - distribution: opensuse-42.3
    vagrant_version: 2.1.0
  - distribution: opensuse-13.2
    vagrant_version: latest
  - distribution: opensuse-13.2
    vagrant_version: 2.1.0

before_install:
  - 'docker pull diodonfrost/${distribution}-ansible:latest'

install:
  - 'pip install molecule==3.0.6 docker==4.2.0 ansible==2.9.7'

script:
  - 'distribution=${distribution} vagrant_version=${vagrant_version} molecule test'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
