---
# tasks file for ansible-role-vagrant

- name: Include OS specific variables.
  include_vars: "{{ ansible_system }}.yml"

- name: Install Vagrant
  include_tasks: "setup-{{ ansible_system }}.yml"
