---
# tasks file for install Vagrant on Linux system

- name: Find all Vagrant version
  uri:
    url: https://releases.hashicorp.com/vagrant/index.json
    return_content: yes
  register: vagrant_index

- name: Find latest Vagrant version when latest var is define
  set_fact:
    vagrant_version: "{{ item }}"
  with_items: "{{ (vagrant_index.content | from_json).versions | list | sort | last }}"
  when: vagrant_version == 'latest'

- name: check if vagrant is present with the right version
  command: vagrant --version
  register: vagrant_installed_version
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: Install Vagrant on Red Hat family system
  package:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm"
    state: present
  when:
    - ansible_os_family == "RedHat"
    - vagrant_version not in vagrant_installed_version.stdout | default('')

- name: Install Vagrant on Suse family system
  zypper:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm"
    disable_gpg_check: yes
    state: present
  when:
    - ansible_os_family == "Suse"
    - vagrant_version not in vagrant_installed_version.stdout | default('')

- name: Install Vagrant on Debian family system
  apt:
    deb: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb"
    state: present
  when:
    - ansible_pkg_mgr == "apt"
    - vagrant_version not in vagrant_installed_version.stdout | default('')

- name: Install Vagrant on Linux with hashicorp generic package
  unarchive:
    src: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_linux_amd64.zip"
    dest: "{{ vagrant_path }}"
    remote_src: yes
  when:
    - ansible_os_family != "RedHat"
    - ansible_os_family != "Suse"
    - ansible_pkg_mgr != "apt"
    - vagrant_version not in vagrant_installed_version.stdout | default('')
