---
# tasks file for install Vagrant on Linux system

- name: check if vagrant is present with the right version
  shell: vagrant --version
  register: vagrant_installed_version
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: Install Vagrant on Red Hat family system
  yum:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm"
    state: present
  when:
    - ansible_os_family == "RedHat"
    - vagrant_version not in vagrant_installed_version

- name: Install Vagrant on Debian family system
  apt:
    deb: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb"
    state: present
  when:
    - ansible_os_family == "Debian"
    - vagrant_version not in vagrant_installed_version

- name: Extract foo.tgz into /var/lib/foo
  unarchive:
    src: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_linux_amd64.zip"
    dest: "{{ vagrant_path }}"
  when:
    - ansible_os_family != "RedHat"
    - ansible_os_family != "Debian"
    - vagrant_version not in vagrant_installed_version
