---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: linux
    image: diodonfrost/${image:-ansible-centos:8}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
    env:
      vagrant_version: "${vagrant_version:-latest}"
provisioner:
  name: ansible
verifier:
  name: ansible
