---
- name: Verify
  hosts: all
  tasks:
    - name: Linux | Vagrant should be functionnal
      command: vagrant --version
      register: vagrant_result

    - name: Linux | Verify commands outputs
      assert:
        that:
          - vagrant_result.rc == 0
        success_msg: "All tests passed"

    - name: Linux | Verify commands outputs
      assert:
        that:
          - vagrant_result.rc == 0
          - ansible_env.vagrant_version in vagrant_result.stdout
        success_msg: "All tests passed"
      when: ansible_env.vagrant_version != "latest"
