---
- name: Verify
  hosts: all
  tasks:
  - name: Windows | Vagrant should be functionnal
    win_command: vagrant --version
    register: vagrant_result

  - name: Windows | Verify commands outputs
    assert:
      that:
        - vagrant_result.rc == 0
      success_msg: "All tests passed"
